---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: aleph
spec:
  hosts:
  - aleph
  http:
  - route:
    - destination:
        host: aleph
        port:
          number: 80
        subset: v02
      weight: 90
    - destination:
        host: aleph
        port:
          number: 80
        subset: v03
      weight: 10

