apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http-front 
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
      app: front
      release: {{ .Release.Name }}