apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: istio-grafana
spec:
  rules:
  - host: grafana.{{ .Values.ingress_ip }}.nip.io
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
