apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: istio-grafana
spec:
  rules:
  - host: grafana.159.8.233.5.nip.io
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
