apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: istio-prometheus
spec:
  rules:
  - host: prometheus.{{ .Values.ingress_ip }}.nip.io
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090
