apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: istio-servicegraph
spec:
  rules:
  - host: servicegraph.159.8.233.5.nip.io
    http:
      paths:
      - backend:
          serviceName: servicegraph
          servicePort: 8088
