apiVersion: otomato.link/v1alpha1
kind: BirdWatch
metadata:
  name: aleph
spec:
  canary_version: v02
  if_unhealthy: rollback
  increment: 2
  deviation: 300
  metric: flask_request_count{endpoint="/version",http_status="500",job="aleph"}
  service: aleph
